name: "dotnet-format-plus"

description: "Run dotnet format & JSCPD and optionally apply any fixes"

branding:
  icon: "navigation-2"
  color: "green"

inputs:
  authToken:
    description: "The GITHUB_TOKEN secret"
    required: true

  action:
    description: "check|fix. The primary action `dotnet format` should perform. `check` for only checking, `fix` will also actually fix the formatting errors in the files."
    required: false
    default: "fix"

  projectFileName:
    description: "The solution or project file to operate on."
    required: false
    default: ""

  onlyChangedFiles:
    description: "Only changed files in the current pull request should be formatted. Only works when the trigger is a pull request."
    required: false
    default: false

  failFast:
    description: "The job should fail if there's a formatting error."
    required: false
    default: true

  workspace:
    description: "The solution or project file to operate on."
    required: true

  nugetConfigPath:
    description: "The path to the NuGet configuration file from workspace. e.g. `NuGet.config`"
    required: false
    default: ""

  severityLevel:
    description: " <error|info|warn> Fixes styles according to formatting rules."
    required: false
    default: "warn"

  logLevel:
    description: "Sets the logging verbosity of the dotnet format process. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]"
    required: false
    default: "detailed"

  problemMatcherEnabled:
    description: "Enable the problem matcher for dotnet format."
    required: false
    default: true

  skipCommit:
    description: "Skip commiting the changes to the repository."
    required: false
    default: false

  commitUserName:
    description: Name used for the commit user
    required: false
    default: "github-actions"

  commitUserEmail:
    description: Email address used for the commit user
    required: false
    default: "bot@users.noreply.github.com"

  commitMessage:
    description: Message used for the commit
    required: false
    default: "🤖 refactor: Apply dotnet-format changes"

  dotnetFormatConfigPath:
    description: "Path to dotnet format config file"
    required: false
    default: ".dotnet-format.json"

  jscpdCheck:
    description: "Run jscpd to check for code duplication"
    required: false
    default: false

  jscpdConfigPath:
    description: "Path to jscpd config file"
    required: false
    default: ".jscpd.json"

  jscpdCheckAsError:
    description: "Fail the build if jscpd finds any code duplication"
    required: false
    default: false

  postNewComment:
    description: "Post a new comment on the pull request or update an existing one with the results"
    required: false
    default: false

outputs:
  hasChanges:
    description: "A value indicating if any files were formatted. If `action` is `check` we will inspect the exit code of `dotnet format` to be <> 0. If `action` is `fix` we see if there are changes to files with `git status -s`."
  hasDuplicates:
    description: "A value indicating if any files were duplicated when `jscpdCheck` is `true`."
runs:
  using: "node16"
  main: "dist/index.js"
