name: "🌞 CI"

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
      - __tests__/dotnet/**
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - __tests__/dotnet/**

jobs:
  check:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: Set Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: "pnpm"

      - run: pnpm install

      - name: Lint & format check
        run: pnpm run format-check

      - name: Test
        run: pnpm test
