name: "🧪 Test dotnet format"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "__tests__/dotnet/**"
    branches:
      - main

jobs:
  dotnet-format:
    name: "🧪 Test dotnet format"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-dotnet
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"
      - name: dotnet-format
        id: dotnet-format
        uses: ./
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          workspace: ${{ github.workspace }}/__tests__/dotnet/Console
          logLevel: "detailed"
          projectFileName: "Console.sln"
          jscpdCheck: true
          jscpdCheckAsError: true

      - name: log-output
        env:
          HAS_CHANGES: ${{ steps.dotnet-format.outputs.hasChanges }}
          HAS_DUPLICATES: ${{ steps.dotnet-format.outputs.hasDuplicates }}
        run: |
          echo "hasChanges=$HAS_CHANGES"
          echo "hasDuplicates=$HAS_DUPLICATES"

  dotnet-format-config:
    name: "🧪 Test dotnet-format with config"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-dotnet
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"
      - name: dotnet-format
        id: dotnet-format
        uses: ./
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          workspace: ${{ github.workspace }}/__tests__/dotnet/ConfigConsoleApp
          projectFileName: "ConfigConsoleApp.sln"
          jscpdCheck: true
          jscpdCheckAsError: true

      - name: log-output
        env:
          HAS_CHANGES: ${{ steps.dotnet-format.outputs.hasChanges }}
          HAS_DUPLICATES: ${{ steps.dotnet-format.outputs.hasDuplicates }}
        run: |
          echo "hasChanges=$HAS_CHANGES"
          echo "hasDuplicates=$HAS_DUPLICATES"
